### ISSUE TITLE
optimize generate sm2 keypair

### ISSUE THREAD

**Issue by Gsealy** [Trisia/alg-sm2-demo#1]
https://github.com/Trisia/alg-sm2-demo/blob/eb3d231804bd2b2c5aa6966c4899f56af1d792f8/src/main/java/edu/hznu/crypto/algsm2demo/SM2KeyGenerateFactory.java#L34

you can use blow code:

```java
final ECGenParameterSpec ecGenSpec = new ECGenParameterSpec("sm2p256v1");
final KeyPairGenerator kpg = KeyPairGenerator.getInstance("EC","BC");
kpg.initialize(ecGenSpec);
final KeyPair kp = kpg.generateKeyPair();
```

BR, 
Gsealy

**Comment by Trisia** [comment]
> https://github.com/Trisia/alg-sm2-demo/blob/eb3d231804bd2b2c5aa6966c4899f56af1d792f8/src/main/java/edu/hznu/crypto/algsm2demo/SM2KeyGenerateFactory.java#L34
> 
> you can use blow code:
> 
> ```java
> final ECGenParameterSpec ecGenSpec = new ECGenParameterSpec("sm2p256v1");
> final KeyPairGenerator kpg = KeyPairGenerator.getInstance("EC","BC");
> kpg.initialize(ecGenSpec);
> final KeyPair kp = kpg.generateKeyPair();
> ```
> 
> BR,
> Gsealy

wow, thank you
